# Generated by Django 3.2.4 on 2021-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insights',
            name='choiceOne',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='insights',
            name='choiceOneTime',
            field=models.IntegerField(default=0),
        ),
    ]
