# Generated by Django 3.2.4 on 2021-07-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210701_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choiceFive',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceFiveTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceFour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceFourTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceOne',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceOneTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceThree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceThreeTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceTwo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='choiceTwoTime',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Insights',
        ),
    ]
