# Generated by Django 3.2.4 on 2021-07-02 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210702_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choiceFive',
            field=models.CharField(default='five', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='choiceFour',
            field=models.CharField(default='four', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='choiceOne',
            field=models.CharField(default='one', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='choiceThree',
            field=models.CharField(default='three', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='choiceTwo',
            field=models.CharField(default='two', max_length=100),
        ),
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
