# Generated by Django 3.2.4 on 2021-07-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210702_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choiceFive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceFiveTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceFour',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceFourTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceOne',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceOneTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceThree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceThreeTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceTwo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='choiceTwoTime',
        ),
        migrations.DeleteModel(
            name='Insights',
        ),
    ]
