from django.db import models
from django.conf import settings
    
    
class Insight(models.Model):
    choiceOne = models.CharField(max_length=100, default="one")
    choiceTwo = models.CharField(max_length=100, default="two")
    choiceThree = models.CharField(max_length=100, default="three")
    choiceFour = models.CharField(max_length=100, default="four")
    choiceFive = models.CharField(max_length=100, default="five")
    choiceSix = models.CharField(max_length=100, default="six")
    choiceSeven = models.CharField(max_length=100, default="Seven")
    choiceEight = models.CharField(max_length=100, default="Eight")
    choiceNine = models.CharField(max_length=100, default="Nine")
    choiceTen = models.CharField(max_length=100, default="Ten")
    choiceEleven = models.CharField(max_length=100, default="Eleven")
    choiceTwelve = models.CharField(max_length=100, default="Twelve")
    choiceThirteen = models.CharField(max_length=100, default="Thirteen")
    choiceFourteen = models.CharField(max_length=100, default="fourteen")
    choiceFifteen = models.CharField(max_length=100, default="Fifteen")
    choiceSixteen = models.CharField(max_length=100, default="Sixteen")
    choiceSeventeen = models.CharField(max_length=100, default="Seventeen")
    choiceEighteen = models.CharField(max_length=100, default="Eighteen")
    choiceNineteen = models.CharField(max_length=100, default="Nineteen")
    choiceTwenty = models.CharField(max_length=100, default="Twenty")
    choiceTwentyOne = models.CharField(max_length=100, default="TwentyOne")
    choiceTwentyTwo = models.CharField(max_length=100, default="TwentyTwo")
    choiceTwentyThree = models.CharField(max_length=100, default="TwentyThree")
    choiceTwentyFour = models.CharField(max_length=100, default="TwentyFour")
    choiceTwentyFive = models.CharField(max_length=100, default="TwentyFive")
    choiceTwentySix = models.CharField(max_length=100, default="TwentySix")
    choiceTwentySeven = models.CharField(max_length=100, default="TwentySeven")
    choiceTwentyEight = models.CharField(max_length=100, default="TwentyEight")
    choiceTwentyNine = models.CharField(max_length=100, default="TwentyNine")
    choiceThirty = models.CharField(max_length=100, default="Thirty")
    choiceThirtyOne = models.CharField(max_length=100, default="ThirtyOne")
