# Generated by Django 3.2.4 on 2021-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceOne', models.CharField(default='one', max_length=100)),
                ('choiceTwo', models.CharField(default='two', max_length=100)),
                ('choiceThree', models.CharField(default='three', max_length=100)),
                ('choiceFour', models.CharField(default='four', max_length=100)),
                ('choiceFive', models.CharField(default='five', max_length=100)),
                ('choiceSix', models.CharField(default='six', max_length=100)),
                ('choiceSeven', models.CharField(default='Seven', max_length=100)),
                ('choiceEight', models.CharField(default='Eight', max_length=100)),
                ('choiceNine', models.CharField(default='Nine', max_length=100)),
                ('choiceTen', models.CharField(default='Ten', max_length=100)),
                ('choiceEleven', models.CharField(default='Eleven', max_length=100)),
                ('choiceTwelve', models.CharField(default='Twelve', max_length=100)),
                ('choiceThirteen', models.CharField(default='Thirteen', max_length=100)),
                ('choiceFourteen', models.CharField(default='fourteen', max_length=100)),
                ('choiceFifteen', models.CharField(default='Fifteen', max_length=100)),
                ('choiceSixteen', models.CharField(default='Sixteen', max_length=100)),
                ('choiceSeventeen', models.CharField(default='Seventeen', max_length=100)),
                ('choiceEighteen', models.CharField(default='Eighteen', max_length=100)),
                ('choiceNineteen', models.CharField(default='Nineteen', max_length=100)),
                ('choiceTwenty', models.CharField(default='Twenty', max_length=100)),
                ('choiceTwentyOne', models.CharField(default='TwentyOne', max_length=100)),
                ('choiceTwentyTwo', models.CharField(default='TwentyTwo', max_length=100)),
                ('choiceTwentyThree', models.CharField(default='TwentyThree', max_length=100)),
                ('choiceTwentyFour', models.CharField(default='TwentyFour', max_length=100)),
                ('choiceTwentyFive', models.CharField(default='TwentyFive', max_length=100)),
                ('choiceTwentySix', models.CharField(default='TwentySix', max_length=100)),
                ('choiceTwentySeven', models.CharField(default='TwentySeven', max_length=100)),
                ('choiceTwentyEight', models.CharField(default='TwentyEight', max_length=100)),
                ('choiceTwentyNine', models.CharField(default='TwentyNine', max_length=100)),
                ('choiceThirty', models.CharField(default='Thirty', max_length=100)),
                ('choiceThirtyOne', models.CharField(default='ThirtyOne', max_length=100)),
            ],
        ),
    ]
