# Generated by Django 3.2.4 on 2021-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceOne', models.CharField(default='one', max_length=100)),
                ('choiceOneTime', models.IntegerField(default=0)),
                ('choiceTwo', models.CharField(default='two', max_length=100)),
                ('choiceTwoTime', models.IntegerField(default=0)),
                ('choiceThree', models.CharField(default='three', max_length=100)),
                ('choiceThreeTime', models.IntegerField(default=0)),
                ('choiceFour', models.CharField(default='four', max_length=100)),
                ('choiceFourTime', models.IntegerField(default=0)),
                ('choiceFive', models.CharField(default='five', max_length=100)),
                ('choiceFiveTime', models.IntegerField(default=0)),
            ],
        ),
    ]
