# Generated by Django 3.2.4 on 2021-07-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insights',
            new_name='Insight',
        ),
    ]
