# Generated by Django 3.2.4 on 2021-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceOneTotal', models.JSONField(default='none')),
                ('choiceTwoTotal', models.JSONField(default='none')),
                ('choiceThreeTotal', models.JSONField(default='none')),
                ('choiceFourTotal', models.JSONField(default='none')),
                ('choiceFiveTotal', models.JSONField(default='none')),
                ('choiceSixTotal', models.JSONField(default='none')),
                ('choiceSevenTotal', models.JSONField(default='none')),
                ('choiceEightTotal', models.JSONField(default='none')),
                ('choiceNineTotal', models.JSONField(default='none')),
                ('choiceTenTotal', models.JSONField(default='none')),
                ('choiceElevenTotal', models.JSONField(default='none')),
                ('choiceTwelveTotal', models.JSONField(default='none')),
                ('choiceThirteenTotal', models.JSONField(default='none')),
                ('choiceFourteenTotal', models.JSONField(default='none')),
                ('choiceFifteenTotal', models.JSONField(default='none')),
                ('choiceSixteenTotal', models.JSONField(default='none')),
                ('choiceSeventeenTotal', models.JSONField(default='none')),
                ('choiceEighteenTotal', models.JSONField(default='none')),
                ('choiceNineteenTotal', models.JSONField(default='none')),
                ('choiceTwentyTotal', models.JSONField(default='none')),
                ('choiceTwentyOneTotal', models.JSONField(default='none')),
                ('choiceTwentyTwoTotal', models.JSONField(default='none')),
                ('choiceTwentyThreeTotal', models.JSONField(default='none')),
                ('choiceTwentyFourTotal', models.JSONField(default='none')),
                ('choiceTwentyFiveTotal', models.JSONField(default='none')),
                ('choiceTwentySixTotal', models.JSONField(default='none')),
                ('choiceTwentySevenTotal', models.JSONField(default='none')),
                ('choiceTwentyEightTotal', models.JSONField(default='none')),
                ('choiceTwentyNineTotal', models.JSONField(default='none')),
                ('choiceThirtyTotal', models.JSONField(default='none')),
                ('choiceThirtyOneTotal', models.JSONField(default='none')),
            ],
        ),
    ]
